export const actionTypes = {
  STORE_SIGN_IN_USER: "STORE_SIGN_IN_USER",
  REMOVE_SIGN_IN_USER: "REMOVE_SIGN_IN_USER",
  ADD_BOOK: "ADD_BOOK",
  SET_BOOKS: "SET_BOOKS",
  DELETE_BOOK: "DELETE_BOOK",
  SET_AUTHORS: "SET_AUTHORS",
  ADD_AUTHOR: "ADD_AUTHOR",
};
